spring.application.name=demo

#These are like custom application properties

#paymentGateway.type = paytm
#paymentGateway.retry-count = 5

payment-property.type = paytm
payment-property.retry-count = 5
payment-property.isEnabled = true
payment-property.timeout = 3000


#--------------------------------------------------------------------
#application.properties
#
# It is the main configuration file of a Spring Boot application.
# It is used to store application settings/configuration.
#
# Spring Boot reads these properties when the application starts.
# We can configure things like:
# - Server port
# - Database connection
# - JPA/Hibernate settings
# - Logging
# - Custom application properties
